# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lazada' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lazada

  target 'lazada-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lazadaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'lazada-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lazada-tvOS

end
